export default{
    setUser(state,payload){
        state.flagSignIn=true;
        state.userId=payload.id;
        state.token=payload.token;
        state.termId=payload.term_id;
        state.deptId=payload.dept_id;
        state.userName=payload.name;
        state.currentLevel=payload.level;
        state.currentTerm=payload.term;
        state.currentSession=payload.session;
        state.hallName=payload.hallName;
        state.hallStatus=payload.hallStatus;
        state.dept=payload.dept;
        state.adviserId=payload.adviserId;
        console.log(state.flagSignIn);
    },
    unsetUser(state){
        state.flagSignIn=false;
        state.userId="";
        state.token="";
        state.termId="";
        state.deptId="";
        state.userName="";
        state.currentLevel="";
        state.currentTerm="";
        state.currentSession="";
        state.hallName="";
        state.hallStatus="";
        state.dept="";
        state.adviserId="";
    },
    setToken(state,token){
        state.token=token;
    },
    setUserInfo(state,payload){
        state.phone=payload.phone;
        state.email=payload.email;
        state.contact_person_name=payload.contact_person_name;
        state.contact_person_number=payload.contact_person_number;
        state.address=payload.address;
    },
    unsetUserInfo(state){
        state.phone="";
        state.email="";
        state.contact_person_name="";
        state.contact_person_number="";
        state.address="";
    },
    setAdviserInfo(state,payload){
        state.adviserName=payload.name;
        state.adviserDesignation=payload.designation;
        state.adviserDept=payload.dept;
    },
    unsetAdviserInfo(state){
        state.adviserName="";
        state.adviserDesignation="";
        state.adviserDept="";
    },
    setCourses(state,payload){
        state.courses=payload;
    },
    setTotalCreditHours(state,payload){
        state.total_credit_hours=payload.total_credit_hours;
    },
    setRegisteredCreditHours(state,payload){
        state.registered_credit_hours=payload.registered_credit_hours;
    },
    setCreditHoursEarnedUptoThisTerm(state,payload){
        state.credit_hours_upto_this_term=payload.credit_hours_earned_upto_this_term;
    },
    setEarnedCreditHoursThisTerm(state,payload){
        state.earned_credit_hours_this_term=payload.earned_credit_hours_this_term;
    },
    setShowFlag(state,payload){
        state.showFlag=payload.showFlag;
    },
    setGradeTermList(state,payload){
        state.gradeTermList=payload;
    },
    setGPA(state,payload){
        state.gpa=payload.gpa;
    },
    setCGPA(state,payload){
        state.cgpa=payload.cgpa;
    }
}